### ISSUE TITLE
`--fix` applies suppressed rules

### ISSUE THREAD

**Issue by alub** [priv-kweihmann/oelint-adv#421]
Hi,

The suppressed rules listed in the configuration are rightly removed from the output (although it seems they are still executed, is there a reason for that?), but running `--fix` edits files with all the rules, not just the ones that remain. That is especially bothersome when using `oelint-adv` for the first time on a codebase as the resulting diff is way too big for review.

I’d be happy to contribute a fix, but I’d first like to understand first why suppressed rules at executed at all.

**Comment by priv-kweihmann** [comment]
That has to be something else.

`fix()` is only called here https://github.com/priv-kweihmann/oelint-adv/blob/2c7341d0eb701983901d3931de2ff063c3176655/oelint_adv/__main__.py#L316 and that function is only run from here https://github.com/priv-kweihmann/oelint-adv/blob/2c7341d0eb701983901d3931de2ff063c3176655/oelint_adv/__main__.py#L348.

Filtering is done since 3.22.4 in the expected way, as `rules` is already prefiltered according to the passed `rulefile`.

So with the latest version, I can't reproduce the issue

**Comment by alub** [comment]
OK, thanks for your answer, I get it now: I don’t use a `rulefile`, I just listed rules with `suppress` in `.oelint.cfg`.

I can easily switch to a rulefile, but what’s the intended use for `suppress`?

**Comment by priv-kweihmann** [comment]
That was initially the idea to suppress findings, the rulefile came - but now I get it, will have a look into the suppression or deprecate the argument
